name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, "unverified"]
assignees:
  - samarmeena
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: You must provide a way to reproduce the problem.
      placeholder: Repo link or code
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Please select the package that the reported issue pertains to.
      options:
        - "discordx"
        - "@discordx/changelog"
        - "@discordx/di"
        - "@discordx/importer"
        - "@discordx/internal"
        - "@discordx/koa"
        - "@discordx/lava-player"
        - "@discordx/music"
        - "@discordx/pagination"
        - "@discordx/utilities"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Stable
        - Dev
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/discordx-ts/discordx/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
