name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, "unverified"]
assignees:
  - vijayymmeena
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: You must provide a way to reproduce the problem.
      placeholder: Repo link or code
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Please select the package that the reported issue pertains to.
      options:
        - "create-discordx"
        - "di"
        - "discordx"
        - "docs"
        - "importer"
        - "internal"
        - "lava-player"
        - "lava-queue"
        - "music"
        - "pagination"
        - "plugin-lava-player"
        - "plugin-ytdl-player"
        - "utilities"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/discordx-ts/discordx/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
