export type DiscordEvent =
  "channelCreate" |
  "channelDelete" |
  "channelPinsUpdate" |
  "channelUpdate" |
  "clientUserGuildSettingsUpdate" |
  "clientUserSettingsUpdate" |
  "debug" |
  "disconnect" |
  "emojiCreate" |
  "emojiDelete" |
  "emojiUpdate" |
  "error" |
  "guildBanAdd" |
  "guildBanRemove" |
  "guildCreate" |
  "guildDelete" |
  "guildMemberAdd" |
  "guildMemberAvailable" |
  "guildMemberRemove" |
  "guildMembersChunk" |
  "guildMemberSpeaking" |
  "guildMemberUpdate" |
  "guildUnavailable" |
  "guildUpdate" |
  "message" |
  "messageDelete" |
  "messageDeleteBulk" |
  "messageReactionAdd" |
  "messageReactionRemove" |
  "messageReactionRemoveAll" |
  "messageUpdate" |
  "presenceUpdate" |
  "rateLimit" |
  "ready" |
  "reconnecting" |
  "resume" |
  "roleCreate" |
  "roleDelete" |
  "roleUpdate" |
  "typingStart" |
  "typingStop" |
  "userNoteUpdate" |
  "userUpdate" |
  "voiceStateUpdate" |
  "warn";
