name: Build - Documentation
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - uses: actions/setup-node@main
        with:
          cache: "npm"
          cache-dependency-path: docs/package-lock.json
          node-version: "lts/*"

      - name: Install dependencies for docs
        run: npm ci
        working-directory: ./docs

      - name: Build docs
        run: npm run build
        working-directory: ./docs
