name: Build - Documentation
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@main
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies for docs
        run: pnpm install
        working-directory: ./docs

      - name: Build docs
        run: pnpm run build
        working-directory: ./docs
