name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build Monorepo
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@main

      - name: Install pnpm
        uses: pnpm/action-setup@master

      - name: Install Node
        uses: actions/setup-node@main
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run check
        run: pnpm check

      - name: Run build:typedoc
        run: pnpm build:typedoc

      - name: Run build
        run: pnpm build

      - name: Run test
        run: pnpm test
