name: Publish - Utilities
on:
  workflow_dispatch:
    inputs:
      version:
        description: "npm version"
        default: "patch"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Synchronize current version
        run: npm version --git-tag-version=false $(npm view @discordx/utilities version)
        working-directory: ./packages/utilities

      - name: Update version
        run: npm version --git-tag-version=false ${{ github.event.inputs.version }}
        working-directory: ./packages/utilities

      - name: Install root dependencies
        run: npm ci

      - name: Install utilities dependencies
        run: npm ci
        working-directory: ./packages/utilities

      - name: Install latest discord.js
        run: npm install discordx@latest discord.js@latest
        working-directory: ./packages/utilities

      - name: Build
        run: npm run build
        working-directory: ./packages/utilities

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/utilities
