name: Publish - Changeset

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: check out code 🛎
        uses: actions/checkout@main

      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: 9.9.0

      - name: Install Node
        uses: actions/setup-node@main
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create Release Pull Request
        uses: changesets/action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        with:
          commit: "chore: release packages"
          publish: pnpm publish -r
          title: "chore: release packages"
